#!/usr/bin/env python3
"""Build the Antigua and Barbuda 2011 Census adapter from the official tables."""
from __future__ import annotations
import argparse, hashlib, json, shutil
from datetime import datetime, timezone
from pathlib import Path
import requests

CENSUS_URL='https://statistics.gov.ag/wp-content/uploads/2017/10/Census-2011-Book-of-Statistical-Tables-I.pdf'
STATS_URL='https://statistics.gov.ag/subjects/population-and-demography/'
GEO_META='https://www.geoboundaries.org/api/current/gbOpen/ATG/ADM1/'
LAW='https://laws.gov.ag/wp-content/uploads/2018/08/a2003-6.pdf'
BUDGET='https://ab.gov.ag/pdf/budget/2026/2026_budget_estimates.pdf'
STRATEGY='https://ab.gov.ag/pdf/budget/2016/2016_budget_speech.pdf'
BARBUDA_PLAN='https://ab.gov.ag/pdf/future_barbuda/future_barbuda-task_2.pdf'
HEALTH_PLAN='https://extranet.who.int/cpcd/sites/default/files/public_file_repository/ATG_Antigua-and-Barbuda_National-Strategic-Plan-For-Health_2016-2020.pdf'

def sha(p:Path): return hashlib.sha256(p.read_bytes()).hexdigest()
def get(url,p):
    if p.exists() and p.stat().st_size:
        return p
    r=requests.get(url,timeout=180,headers={'User-Agent':'AreaData/0.10.2 source collector'});r.raise_for_status();p.parent.mkdir(parents=True,exist_ok=True);p.write_bytes(r.content);return p
def pct(n,d): return None if not d else round(n/d*100,4)

PARISH={
 'Saint John':dict(pop=51737,male=24792,female=26945,households=18447,elec=436+172+7233+9961,water=1377+17+5424+280+553+14+7161+563,bath=5937+9092,education_total=16593+22258,education_none=123+134,active=9953+1543+13704+1441,unemployed=1543+1441,born_total=21643+29486,born_abroad=7886+10158),
 'Saint George':dict(pop=8055,male=3826,female=4229,households=2932,elec=29+2785,water=122+4+2238+129,bath=2514,education_total=6152,education_none=28,active=3882+349,unemployed=349,born_total=7976,born_abroad=2051),
 'Saint Peter':dict(pop=5325,male=2538,female=2787,households=1829,elec=18+1668,water=114+8+1226+163,bath=1487,education_total=4012,education_none=40,active=2419+281,unemployed=281,born_total=5317,born_abroad=1147),
 'Saint Philip':dict(pop=3347,male=1579,female=1768,households=1139,elec=17+1055,water=41+0+789+107,bath=898,education_total=2572,education_none=27,active=1448+114,unemployed=114,born_total=3322,born_abroad=642),
 'Saint Paul':dict(pop=8128,male=3857,female=4271,households=2809,elec=71+2572,water=179+4+1716+99,bath=2304,education_total=6124,education_none=46,active=3738+366,unemployed=366,born_total=8116,born_abroad=1892),
 'Saint Mary':dict(pop=7341,male=3533,female=3808,households=2512,elec=51+2308,water=192+5+1528+164,bath=1971,education_total=5542,education_none=60,active=3391+341,unemployed=341,born_total=7331,born_abroad=1666),
 'Barbuda':dict(pop=1634,male=861,female=773,households=545,elec=2+522,water=1+1+182+70,bath=432,education_total=1162,education_none=4,active=859+40,unemployed=40,born_total=1625,born_abroad=172),
 'Redonda':dict(pop=None,male=None,female=None,households=None,elec=None,water=None,bath=None,education_total=None,education_none=None,active=None,unemployed=None,born_total=None,born_abroad=None)
}
NATIONAL=dict(pop=85567,male=40986,female=44581,households=30213,elec=436+28104,water=2579+53+20264+1575,bath=24635,education_total=64416,education_none=461,active=39395+4475,unemployed=4475,born_total=84816,born_abroad=25615)

def main():
 p=argparse.ArgumentParser();p.add_argument('--project',required=True);p.add_argument('--out',required=True);a=p.parse_args();root=Path(a.project).resolve();out=Path(a.out).resolve();out.mkdir(parents=True,exist_ok=True)
 source=root/'raw/discovered-source-files/ATG/001-Census_2011_Book_of_Statistical_Tables_I.pdf'
 if not source.exists(): get(CENSUS_URL,source)
 raw=root/'raw/antigua-barbuda-country-edition';raw.mkdir(parents=True,exist_ok=True)
 census=raw/'Census_2011_Book_of_Statistical_Tables_I.pdf';shutil.copy2(source,census)
 meta=requests.get(GEO_META,timeout=120,headers={'User-Agent':'AreaData/0.10.2 source collector'}).json(); geo=get(meta['simplifiedGeometryGeoJSON'],raw/'geoBoundaries-ATG-ADM1_simplified.geojson'); gj=json.loads(geo.read_text(encoding='utf-8'))
 planning=[]
 for url,name in [(LAW,'physical-planning-act-2003.pdf'),(BUDGET,'budget-estimates-2026.pdf'),(STRATEGY,'budget-speech-and-development-strategy-2016.pdf'),(BARBUDA_PLAN,'future-barbuda-development-plan-vol4.pdf'),(HEALTH_PLAN,'national-health-strategy-2016-2020.pdf')]:
  planning.append(get(url,raw/name))
 names={f['properties']['shapeName']:f for f in gj['features']}; expected=set(PARISH)
 if set(names)!=expected: raise RuntimeError(f'Unexpected boundary names {set(names)^expected}')
 territories=[];features=[];ids={}
 for name in sorted(expected):
  f=names[name];props=f['properties'];tid=f"ATG:C2011:ADM1:{props['shapeISO'].split('-')[-1]}";ids[name]=tid
  territories.append({'id':tid,'country_id':'ATG','name':name,'level':'parish_dependency','type':'parish','parent_id':'ATG','official_code':props['shapeISO'],'code_system':'ISO 3166-2','boundary_version':'geoBoundaries ATG ADM1 2009 / build 2023-12-12','valid_from':'2009-01-01','geography_note':'Reference boundary. Census City and Rural rows for Saint John are combined to this parish; Redonda has no published row in the adopted Census tables.'})
  features.append({'type':'Feature','properties':{'territory_id':tid,'source_id':'atg-geoboundaries-adm1-2009','official_code':props['shapeISO'],'code_system':'ISO 3166-2','geometry_edition':'geoBoundaries ATG ADM1 2009','join_method':'Exact published parish/dependency name; Saint John Census rows summed before join','reference_only':True},'geometry':f['geometry']})
 rows={'ATG':NATIONAL,**{ids[k]:v for k,v in PARISH.items()}}
 source_id='atg-statistics-census-2011'
 specs=[
  ('ATG_C2011_POP_TOTAL','Census resident population','Population','people',lambda r:r['pop'],'sum','Total resident population; institutional population is included.'),
  ('ATG_C2011_FEMALE_PCT','Female population','Population','%',lambda r:pct(r['female'],r['pop']) if r['female'] is not None else None,'none','Female residents as a share of the resident Census population.'),
  ('ATG_C2011_HOUSEHOLDS','Non-institutional households','Households and housing','households',lambda r:r['households'],'sum','Households in the non-institutional housing tables.'),
  ('ATG_C2011_PUBLIC_WATER_PCT','Households using a public water source','Water','% of households',lambda r:pct(r['water'],r['households']) if r['water'] is not None else None,'none','Households whose main water source is public standpipe, public well/tank, or public piped supply into dwelling or yard.'),
  ('ATG_C2011_ELECTRICITY_PCT','Households using public electricity or a private generator','Basic services','% of households',lambda r:pct(r['elec'],r['households']) if r['elec'] is not None else None,'none','Households reporting public electricity or a private generator as the source of lighting.'),
  ('ATG_C2011_BATHROOM_INSIDE_PCT','Households with a bathroom inside the dwelling','Sanitation','% of households',lambda r:pct(r['bath'],r['households']) if r['bath'] is not None else None,'none','Households with a bathroom inside the dwelling. This is a bathroom-location indicator, not a sewer-connection rate.'),
  ('ATG_C2011_NO_EDUCATION_PCT','Population age 15+ with no education level','Education','% of population age 15+',lambda r:pct(r['education_none'],r['education_total']) if r['education_none'] is not None else None,'none','Population age 15 or older whose highest education level attained is none.'),
  ('ATG_C2011_UNEMPLOYMENT_RATE','Unemployment rate','Employment','% of active population',lambda r:pct(r['unemployed'],r['active']) if r['unemployed'] is not None else None,'none','Unemployed people as a share of the active population at Census Day.'),
  ('ATG_C2011_FOREIGN_BORN_PCT','Foreign-born population','Migration','% of non-institutional population',lambda r:pct(r['born_abroad'],r['born_total']) if r['born_abroad'] is not None else None,'none','People born abroad as a share of the non-institutional population with stated or unstated birthplace.'),
 ]
 indicators=[];observations=[]
 for iid,name,theme,unit,calc,aggregation,definition in specs:
  indicators.append({'id':iid,'name':name,'theme':theme,'unit':unit,'definition':definition,'definition_id':'ATG-CENSUS-2011','population':'Published 2011 Census universe stated for each table','measurement_method':'source_reported' if aggregation=='sum' else 'derived_from_source_counts','aggregation':aggregation,'period_policy':'fixed_source_period','series_family':'census','display_role':'primary','source_id':source_id,'source_locator':'2011 Census Book of Statistical Tables I: Tables 1.1a, 1.4a, 1.5a, 1.9a, 5.1, 8.2, 9.5 and 11.9'})
  for tid,r in rows.items():
   v=calc(r);observations.append({'territory_id':tid,'indicator_id':iid,'period':'2011','value':v,'status':'observed' if v is not None else 'missing','source_id':source_id,'definition':definition,'definition_id':'ATG-CENSUS-2011','unit':unit,'population':'Published 2011 Census universe stated for each table','measurement_method':'source_reported' if aggregation=='sum' else 'derived_from_source_counts','source_locator':'2011 Census Book of Statistical Tables I: selected published table rows'})
 national_specs=[
  ('ATG_C2011_SEEING_DIFFICULTY_PCT','Population reporting difficulty seeing','Disability','% of stated non-institutional population',pct(4790+697+114,84816-1672),'At least some difficulty seeing among the population with stated seeing-difficulty status.','2011','atg-statistics-census-2011'),
  ('ATG_C2011_AFRICAN_DESCENT_PCT','Population of African descent','Ethnicity','% of non-institutional population',pct(74018,84816),'African-descendent ethnic group as a share of the non-institutional population.','2011','atg-statistics-census-2011'),
  ('ATG_C2011_UNINSURED_PCT','Population without health insurance','Health','% of population with stated insurance status',pct(41370,42012+41370),'People reported not insured among people with stated insured or not-insured status.','2011','atg-statistics-census-2011'),
  ('ATG_C2011_STJOHN_CITY_SHARE','Population in St. John City enumeration parish','Settlement','% of resident Census population',pct(22219,85567),'Residents in the published St. John City enumeration parish as a share of resident population. This is not a national urbanization rate.','2011','atg-statistics-census-2011'),
  ('ATG_HEALTH2014_CHILD_UNDERNUTRITION','Child undernutrition recorded at public clinics','Nutrition','% of children age 0-4 attending public clinics',2.9,'Children age 0-4 attending public clinics reported with undernutrition in the national health strategy.','2014','atg-national-health-strategy'),
  ('ATG_C2011_PUBLIC_ASSISTANCE_LIVELIHOOD','Other public assistance as a source of livelihood','Poverty and livelihoods','% of population age 15+',pct(160,64416),'People age 15+ reporting other public assistance as a source of livelihood. This is not a poverty headcount.','2011','atg-statistics-census-2011')]
 for iid,name,theme,unit,value,definition,period,sid in national_specs:
  indicators.append({'id':iid,'name':name,'theme':theme,'unit':unit,'definition':definition,'definition_id':iid,'population':unit.replace('% of ',''),'measurement_method':'source_reported' if value in (2.9,) else 'derived_from_source_counts','aggregation':'none','period_policy':'fixed_source_period','series_family':'survey' if sid!='atg-statistics-census-2011' else 'census','display_role':'primary','source_id':sid,'source_locator':'National health strategy p.15' if sid!='atg-statistics-census-2011' else '2011 Census Book of Statistical Tables I: Tables 5.1, 5.9, 6.1, 6.2 and 14.1'})
  observations.append({'territory_id':'ATG','indicator_id':iid,'period':period,'value':value,'status':'observed','source_id':sid,'definition':definition,'definition_id':iid,'unit':unit,'population':unit.replace('% of ',''),'measurement_method':'source_reported' if value==2.9 else 'derived_from_source_counts','source_locator':'National health strategy p.15' if sid!='atg-statistics-census-2011' else '2011 Census Book of Statistical Tables I: selected national row'})
 today=datetime.now(timezone.utc).date().isoformat()
 sources=[
  {'id':source_id,'name':'2011 Population and Housing Census - Book of Statistical Tables I','publisher':'Statistics Division, Government of Antigua and Barbuda','url':CENSUS_URL,'status':'ready','retrieved_at':today,'reference_period':'2011','geographic_level':'country and parish/dependency','raw_path':'raw/antigua-barbuda-country-edition/Census_2011_Book_of_Statistical_Tables_I.pdf','sha256':sha(census),'license':'Official public report; source attribution retained.','note':'Published parish tables are integrated. Saint John City and Rural are summed to the ADM1 parish for the map; the original two rows remain identified in source locators.'},
  {'id':'atg-geoboundaries-adm1-2009','name':'geoBoundaries ATG ADM1 reference boundaries','publisher':'geoBoundaries / source credited as Wikimedia','url':meta['simplifiedGeometryGeoJSON'],'status':'ready','retrieved_at':today,'reference_period':'2009 representation / 2023 build','geographic_level':'parish and dependency','raw_path':'raw/antigua-barbuda-country-edition/geoBoundaries-ATG-ADM1_simplified.geojson','sha256':sha(geo),'license':meta['boundaryLicense'],'note':'Reference-only boundaries. They are not presented as an official legal boundary certification.'},
  {'id':'atg-national-health-strategy','name':'National Strategic Plan for Health 2016-2020','publisher':'Government of Antigua and Barbuda, Ministry of Health and the Environment','url':HEALTH_PLAN,'status':'ready','retrieved_at':today,'reference_period':'2016-2020; cited nutrition observation 2014','geographic_level':'country','raw_path':'raw/antigua-barbuda-country-edition/national-health-strategy-2016-2020.pdf','sha256':sha(raw/'national-health-strategy-2016-2020.pdf'),'license':'Official plan hosted by WHO; source attribution retained.'},
 ]
 comparisons=[{'parent_id':'ATG','member_ids':[ids[x] for x in sorted(ids)],'label':'Parishes and dependencies','membership_note':'Eight ADM1 reference areas. Saint John combines the City and Rural Census rows; Redonda remains with explicit missing Census values.','source_ids':['atg-geoboundaries-adm1-2009',source_id]}]
 bundle={'schema_version':'1.0','country_area_id':'ATG','period':'2011','replace_country_branch':True,'territories':territories,'terminal_territory_ids':list(ids.values()),'comparisons':comparisons,'indicators':indicators,'observations':observations,'boundaries':{'type':'FeatureCollection','features':features},'sources':sources}
 (out/'antigua-barbuda-country-depth-bundle.json').write_text(json.dumps(bundle,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
 catalog=[{'table_id':x,'table_title':x,'numeric_cell_count':1,'source_path':'raw/antigua-barbuda-country-edition/Census_2011_Book_of_Statistical_Tables_I.pdf'} for x in ['Table 1.1a Households by parish and dwelling type','Table 1.4a Households by parish and lighting source','Table 1.5a Households by parish and water source','Table 1.9a Households by parish and bathroom location','Table 5.1 Population by parish, census year and sex','Table 5.9 Population by age, ethnicity and sex','Table 6.1 Disability by degree, type and sex','Table 6.2 Health insurance by age and sex','Table 8.2 Population by parish, birthplace and sex','Table 9.5 Education level by parish','Table 11.9 Employment status by parish','Table 14.1 Sources of livelihood']]
 files=[{'name':x.name,'bytes':x.stat().st_size,'sha256':sha(x)} for x in [census,geo,*planning]]
 audit={'schema_version':'1.0','status':'complete','counts':{'parishes_and_dependencies':8,'boundary_features':8,'indicators':len(indicators),'observations':len(observations),'catalogued_tables':len(catalog)},'controls':{'saint_john_combined':True,'redonda_missing_not_zero':True,'national_supplements_not_imputed':True},'source_receipts':files}
 (out/'ATG_COLLECTION_AUDIT.json').write_text(json.dumps(audit,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
 manifest={'schema_version':'1.0','country_area_id':'ATG','scope_role':'completed Antigua and Barbuda edition with 2011 Census parish adapter','country_adapter_status':'complete_country_adapter','official_census_url':CENSUS_URL,'census_source_id':source_id,'semantic_source_path':'raw/antigua-barbuda-country-edition/Census_2011_Book_of_Statistical_Tables_I.pdf','audit_path':'evidence/ATG_INTEGRATION_AUDIT.json','domains':{
  'official_statistics_office':{'status':'inspected','urls':[STATS_URL],'note':'The official Statistics Division Census and population publication pages were inspected.','evidence':[{'raw':'raw/discovered-source-files/ATG'},{'audit':'evidence/ATG_INTEGRATION_AUDIT.json'}]},
  'latest_census':{'status':'adopted','urls':[CENSUS_URL,'https://statistics.gov.ag/census/'],'note':'The 2011 Census remains the latest completed round with a published final table book; the official site reports 2025 field operations, not adopted final results.','evidence':[{'raw':'raw/antigua-barbuda-country-edition/Census_2011_Book_of_Statistical_Tables_I.pdf'}]},
  'census_results':{'status':'adopted','urls':[CENSUS_URL],'note':'Selected official 2011 Census tables are integrated for the country and seven resident parish/dependency rows; Redonda remains explicit missing.','evidence':[{'raw':'raw/antigua-barbuda-country-edition/Census_2011_Book_of_Statistical_Tables_I.pdf'}]},
  'table_catalog':{'status':'inspected','urls':[CENSUS_URL],'note':'The published table book contents and every adopted table are catalogued; unselected tables remain retained in the source PDF.','evidence':[{'audit':'evidence/ATG_INTEGRATION_AUDIT.json'}]},
  'machine_readable_data':{'status':'adopted','urls':[CENSUS_URL],'note':'Published PDF tables were extracted into a source-attributed normalized country bundle; source cells and derived percentages retain table locators.','evidence':[{'audit':'evidence/ATG_INTEGRATION_AUDIT.json'}]},
  'administrative_codes':{'status':'geography_matched','urls':[GEO_META,CENSUS_URL],'note':'Published Census parish/dependency names were matched to eight ISO 3166-2-coded ADM1 reference areas. Saint John City and Rural were summed before the parish join.','evidence':[{'raw':'raw/antigua-barbuda-country-edition/geoBoundaries-ATG-ADM1_simplified.geojson'}]},
  'adm1_adm2_boundaries':{'status':'adopted','urls':[GEO_META],'note':'Eight source-attributed reference ADM1 shapes are integrated and explicitly labelled non-certifying; no ADM2 layer is claimed.','evidence':[{'raw':'raw/antigua-barbuda-country-edition/geoBoundaries-ATG-ADM1_simplified.geojson'}]},
  'planning_law':{'status':'inspected','urls':[LAW],'note':'The official Ministry of Legal Affairs publication of the Physical Planning Act 2003 was acquired and inspected; it assigns development-plan preparation under Part III.','evidence':[{'raw':'raw/antigua-barbuda-country-edition/physical-planning-act-2003.pdf'}]},
  'planning_guidance':{'status':'acquired','urls':[BARBUDA_PLAN,STRATEGY],'note':'Official development-strategy and Barbuda development-plan materials were acquired as guidance and examples; they are not represented as a current plan for every parish.','evidence':[{'raw':'raw/antigua-barbuda-country-edition'}]},
  'plans_budgets_implementation_evaluation':{'status':'acquired','urls':[BUDGET,STRATEGY,BARBUDA_PLAN],'note':'The official 2026 recurrent/development estimates, strategy appendix and Barbuda plan were acquired. Their presence is not treated as proof of completed implementation or official evaluation.','evidence':[{'raw':'raw/antigua-barbuda-country-edition'}]}},
 'recent_census_rounds':[{'round':'2020','date_text':'2025 Census field operations; final results not yet adopted','year':2025,'url':'https://statistics.gov.ag/census/'},{'round':'2010','date_text':'2011 Population and Housing Census','year':2011,'url':CENSUS_URL},{'round':'2000','date_text':'2001 Population and Housing Census','year':2001,'url':'https://statistics.gov.ag/wp-content/uploads/2017/11/2001-Census-of-Population-and-Housing.pdf'}],
 'indicator_themes':{'ATG_C2011_POP_TOTAL':'population_total','ATG_C2011_FEMALE_PCT':'age_sex','ATG_C2011_HOUSEHOLDS':'households_housing','ATG_C2011_PUBLIC_WATER_PCT':'drinking_water','ATG_C2011_BATHROOM_INSIDE_PCT':'sanitation','ATG_C2011_ELECTRICITY_PCT':'electricity','ATG_C2011_NO_EDUCATION_PCT':'education_literacy','ATG_C2011_UNEMPLOYMENT_RATE':'employment','ATG_C2011_SEEING_DIFFICULTY_PCT':'disability','ATG_C2011_FOREIGN_BORN_PCT':'migration','ATG_C2011_STJOHN_CITY_SHARE':'urban_rural','ATG_C2011_AFRICAN_DESCENT_PCT':'ethnicity','ATG_C2011_UNINSURED_PCT':'health','ATG_HEALTH2014_CHILD_UNDERNUTRITION':'nutrition','ATG_C2011_PUBLIC_ASSISTANCE_LIVELIHOOD':'poverty'},
 'theme_reasons':{'urban_rural':'The published City enumeration-parish share is integrated with an explicit warning that it is not a national urbanization rate.','poverty':'The public-assistance livelihood indicator is integrated as a vulnerability measure and explicitly is not labelled as a poverty headcount.','nutrition':'The national health strategy value retains its 2014 clinic-attendee universe and is not copied to parishes.'},
 'semantic_catalog':catalog,'sources':[
  {'id':'atg-physical-planning-act','name':'Physical Planning Act 2003','publisher':'Ministry of Legal Affairs, Antigua and Barbuda','url':LAW,'status':'ready','retrieved_at':today,'reference_period':'2003, with later amendment noted separately','geographic_level':'national legal framework','raw_path':'raw/antigua-barbuda-country-edition/physical-planning-act-2003.pdf','sha256':sha(raw/'physical-planning-act-2003.pdf'),'license':'Official legal publication.'},
  {'id':'atg-budget-2026','name':'Antigua and Barbuda Budget Estimates 2026','publisher':'Government of Antigua and Barbuda','url':BUDGET,'status':'ready','retrieved_at':today,'reference_period':'2026 budget; includes 2024 actual and 2025 original/revised','geographic_level':'national budget','raw_path':'raw/antigua-barbuda-country-edition/budget-estimates-2026.pdf','sha256':sha(raw/'budget-estimates-2026.pdf'),'license':'Official public budget; source attribution retained.'},
  {'id':'atg-development-strategy-2016','name':'Strategy for Economic Development 2016-2020','publisher':'Government of Antigua and Barbuda','url':STRATEGY,'status':'ready','retrieved_at':today,'reference_period':'2016-2020','geographic_level':'national strategy','raw_path':'raw/antigua-barbuda-country-edition/budget-speech-and-development-strategy-2016.pdf','sha256':sha(raw/'budget-speech-and-development-strategy-2016.pdf'),'license':'Official public budget speech appendix; source attribution retained.'},
  {'id':'atg-barbuda-plan','name':'Future Barbuda Draft Development Plan and Design Brief, Volume 4','publisher':'Government of Antigua and Barbuda / Barbuda Council','url':BARBUDA_PLAN,'status':'ready','retrieved_at':today,'reference_period':'draft publication retrieved 2026','geographic_level':'Barbuda','raw_path':'raw/antigua-barbuda-country-edition/future-barbuda-development-plan-vol4.pdf','sha256':sha(raw/'future-barbuda-development-plan-vol4.pdf'),'license':'Official public planning document; source attribution retained.'}],
 'documents':[
  {'id':'atg-physical-planning-act','territory_id':'ATG','category':'reference','title':'Physical Planning Act 2003','kind':'official-law','url':LAW,'availability':'body_acquired','official_status':'unverified','source_id':'atg-physical-planning-act'},
  {'id':'atg-development-strategy','territory_id':'ATG','category':'plan','title':'Strategy for Economic Development 2016-2020','kind':'official-strategy','url':STRATEGY,'availability':'body_acquired','official_status':'unverified','source_id':'atg-development-strategy-2016'},
  {'id':'atg-budget-2026','territory_id':'ATG','category':'budget','title':'Recurrent and Development Budget Estimates 2026','kind':'official-budget','url':BUDGET,'availability':'body_acquired','official_status':'unverified','source_id':'atg-budget-2026'},
  {'id':'atg-barbuda-plan','territory_id':ids['Barbuda'],'category':'plan','title':'Future Barbuda Draft Development Plan and Design Brief, Volume 4','kind':'official-draft-plan','url':BARBUDA_PLAN,'availability':'body_acquired','official_status':'unverified','source_id':'atg-barbuda-plan'}],
 'census_history':{'country_id':'ATG','names':{'en':'Antigua and Barbuda','es':'Antigua y Barbuda','ja':'アンティグア・バーブーダ'},'adopted_data_year':2011,'adopted_source_url':CENSUS_URL,'official_census_url':'https://statistics.gov.ag/census/','recent_rounds':[{'year':2025,'status':'fieldwork_no_final_results_adopted','url':'https://statistics.gov.ag/census/'},{'year':2011,'status':'results_adopted','url':CENSUS_URL},{'year':2001,'status':'historical_round','url':'https://statistics.gov.ag/wp-content/uploads/2017/11/2001-Census-of-Population-and-Housing.pdf'}],'note':{'en':'AreaData adopts the final 2011 table book. The official site reports 2025 field operations, but no final 2025 result is substituted.','es':'AreaData adopta el libro de cuadros final de 2011. El sitio oficial informa trabajo de campo en 2025, sin sustituir resultados finales inexistentes.','ja':'AreaDataでは2011年の確定表を採用します。公式サイトの2025年調査実施情報は、未公表の確定結果として代用しません。'}},
 'adapters':['atg-census-2011-depth','atg-planning-evidence'],'collection_notes':['ATG: official 2011 Census tables connect the country and seven resident parish/dependency rows; Saint John City and Rural are summed to the mapped parish, while Redonda remains explicit missing.','ATG: nutrition and selected health/vulnerability measures retain national source universes and are not imputed to parishes.'],
 'inventory_method':'The official PDF table book is preserved by hash. Every adopted table/field has an explicit semantic record; catalogued but unselected tables remain non-adopted with a reason.',
 'audit':audit}
 (out/'ATG_COMPLETION_MANIFEST.json').write_text(json.dumps(manifest,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
 print(json.dumps(audit,indent=2))
if __name__=='__main__': main()
